#!/usr/bin/env python3
from astropy.io import fits
from xisf import XISF
import argparse
import json

parser = argparse.ArgumentParser(description='Convert FITS files to XISF')
parser.add_argument('fits_file')
parser.add_argument('xisf_file')

parser.add_argument('-c', '--compression-type', choices=['zlib', 'lz4', 'lz4hc','zstd'], default='zstd')
parser.add_argument('-l', '--compression-level', type=int, default='2')
parser.add_argument('-s', '--shuffle', action='store_true')
args = parser.parse_args()

fits_file = fits.open(args.fits_file)

fitskwds = dict()
image_header = fits_file[0].header
for hdr in image_header:
    value = image_header[hdr]
    if type(value) is bool:
        value = 'true' if value else 'false'
    else:
        value = str(value)
    fitskwds[hdr] = [{ 'value': value, 'comment': image_header.comments[hdr]}]

fitskwds = { 'FITSKeywords': fitskwds }

image_data = fits_file[0].data
if len(image_data.shape) < 3:
    image_data.shape = (image_data.shape[0], image_data.shape[1], 1)

XISF.write(args.xisf_file, fits_file[0].data, None, fitskwds, None, codec=args.compression_type, shuffle=args.shuffle, level=args.compression_level)
