#!/usr/bin/env python3 
import argparse
import json
from astropy.io import fits

parser = argparse.ArgumentParser(description='Add keywords to FITS files')

parser.add_argument('keyword')
parser.add_argument('value')
parser.add_argument('--comment', default='')

parser.add_argument('files', nargs='+')

args = parser.parse_args()

for filename in args.files:
    file = fits.open(filename)
    file[0].header[args.keyword] = (args.value, args.comment)
    file.writeto(filename, overwrite=True)


