#!/usr/bin/env python3 
from xisf import XISF
import argparse
import json

parser = argparse.ArgumentParser(description='Add FITS keywords to XISF files')

parser.add_argument('keyword')
parser.add_argument('value')
parser.add_argument('--comment', default='')

parser.add_argument('files', nargs='+')

parser.add_argument('-c', '--compression-type', choices=['zlib', 'lz4', 'lz4hc','zstd'], default='zstd')
parser.add_argument('-l', '--compression-level', type=int, default='2')
parser.add_argument('-s', '--shuffle', action='store_true')
args = parser.parse_args()

for filename in args.files:
    file = XISF(filename)
    ims_meta = file.get_images_metadata()
    ims_meta[0]['FITSKeywords'][args.keyword] = [
        {
            'value': args.value,
            'comment': args.comment,
        }
    ]

    XISF.write(filename, file.read_image(0), None, ims_meta[0], file.get_file_metadata(), codec=args.compression_type, shuffle=args.shuffle, level=args.compression_level)

