#!/usr/bin/env python3 
from xisf import XISF
from yaml import dump, Dumper
import json
import argparse

parser = argparse.ArgumentParser(description='xisf headers util')
parser.add_argument('files', nargs='+')
parser.add_argument('-y', '--yaml', action='store_true')
parser.add_argument('-k','--fits-keyword', action='append')
args = parser.parse_args()

results = dict()
for filename in args.files:
    file = XISF(filename)
    ims_meta = file.get_images_metadata()
    if args.fits_keyword:
        results[filename] = dict()
        for keyword in args.fits_keyword:
            if keyword in ims_meta[0]['FITSKeywords']:
                results[filename][keyword] = ims_meta[0]['FITSKeywords'][keyword][0]['value']
    else:
        results[filename] = ims_meta


if args.yaml:
    print(dump(results, Dumper=Dumper))
else:
    print(json.dumps(results, indent=4, default=str))

