#!/usr/bin/env python3 
from xisf import XISF
from yaml import dump, Dumper
import json
import argparse

parser = argparse.ArgumentParser(description='xisf headers util')
parser.add_argument('file')
parser.add_argument('-f', '--format', choices=['json', 'yaml'], default='json')
args = parser.parse_args()

file = XISF(args.file)
ims_meta = file.get_images_metadata()

if args.format == 'yaml':
    print(dump(ims_meta, Dumper=Dumper))
else:
    print(json.dumps(ims_meta, indent=4, default=str))

